env:
  - POSTGRESQL_VERSION=9.6
  - POSTGRESQL_VERSION=10
  - POSTGRESQL_VERSION=11
  - POSTGRESQL_VERSION=12
before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - bin/travis_db_setup
branches:
  only:
    - master
install:
  - travis_retry bin/setup
language:
  - ruby
notifications:
  email: false
rvm:
  - 2.3
  - 2.4
  - 2.6
  - 2.5
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails60.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  fast_finish: true
  allow_failures:
    - gemfile: gemfiles/rails_edge.gemfile
  exclude:
    - rvm: 2.3
      gemfile: gemfiles/rails60.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails60.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_edge.gemfile
